apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: biscuits-frontend-ingress
spec:
  rules:
  - http:
      paths:
      - path: /admin
        backend:
          serviceName: biscuits-admin
          servicePort: 8080
